import type { Metadata } from "next";
import "./globals.css";
import { LayoutWrapper } from "./Components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className="pt-[140px]">
        <LayoutWrapper>{children}</LayoutWrapper>
        
      </body>
    </html>
  );
}
